name: goapitest
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  build_runner: ^2.4.6
  provider: ^6.0.5
  dio: ^5.3.0
  http: ^1.1.0
  mockito: ^5.4.2
  persistent_bottom_nav_bar: ^5.0.2
  kartal: ^3.2.0
  badges: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  test: ^1.24.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/
